### ISSUE TITLE
failed to compile

### ISSUE THREAD

**Issue by eskuai** [making/uaa-ui#4]
````
main:
     [echo] NPM RUN BUILD!
     [exec]
     [exec] > ui@0.1.0 build /root/uaa-ui/ui
     [exec] > react-scripts build && rm -rf ../target/classes/static && mkdir -p ../target/classes/static && mv build/* ../target/classes/static/
     [exec]
     [exec] sh: react-scripts: command not found
     [exec]
     [exec] npm ERR! Linux 3.10.0-957.5.1.el7.x86_64
     [exec] npm ERR! argv "/usr/bin/node" "/bin/npm" "run" "build"
     [exec] npm ERR! node v6.17.1
     [exec] npm ERR! npm  v3.10.10
     [exec] npm ERR! file sh
     [exec] npm ERR! code ELIFECYCLE
     [exec] npm ERR! errno ENOENT
     [exec] npm ERR! syscall spawn
     [exec] npm ERR! ui@0.1.0 build: `react-scripts build && rm -rf ../target/classes/static && mkdir -p ../target/classes/static && mv build/* ../target/classes/static/`
     [exec] npm ERR! spawn ENOENT
     [exec] npm ERR!
     [exec] npm ERR! Failed at the ui@0.1.0 build script 'react-scripts build && rm -rf ../target/classes/static && mkdir -p ../target/classes/static && mv build/* ../target/classes/static/'.
     [exec] npm ERR! Make sure you have the latest version of node.js and npm installed.
     [exec] npm ERR! If you do, this is most likely a problem with the ui package,
     [exec] npm ERR! not with npm itself.
     [exec] npm ERR! Tell the author that this fails on your system:
     [exec] npm ERR!     react-scripts build && rm -rf ../target/classes/static && mkdir -p ../target/classes/static && mv build/* ../target/classes/static/
     [exec] npm ERR! You can get information on how to open an issue for this project with:
     [exec] npm ERR!     npm bugs ui
     [exec] npm ERR! Or if that isn't available, you can get their info via:
     [exec] npm ERR!     npm owner ls ui
     [exec] npm ERR! There is likely additional logging output above.
     [exec] npm WARN Local package.json exists, but node_modules missing, did you mean to install?
     [exec]
     [exec] npm ERR! Please include the following file with any support request:
     [exec] npm ERR!     /root/uaa-ui/ui/npm-debug.log
````

**Comment by making** [comment]
look

>      [exec] sh: react-scripts: command not found

**Comment by making** [comment]
If you want to try it without compiling, you can use my docker image

For Cloud Foundry

```yaml
applications:
- name: uaa-ui
  disk_quota: 2g
  docker:
    image: making/uaa-ui
  env:
    CA_CERTS: |
      -----BEGIN CERTIFICATE-----
      CA for UAA
      -----END CERTIFICATE-----
```

For k8s

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: uaa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uaa-ui
  namespace: uaa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uaa-ui
  template:
    metadata:
      labels:
        app: uaa-ui
    spec:
      containers:
      - image: making/uaa-ui
        name: uaa-ui
        ports:
        - containerPort: 8080
        env:
        - name: CA_CERT
          value: |
            -----BEGIN CERTIFICATE-----
            CA for UAA
            -----END CERTIFICATE-----
---
kind: Service
apiVersion: v1
metadata:
  name: uaa-ui
  namespace: uaa
spec:
  type: LoadBalancer
  selector:
    app: uaa-ui
  ports:
  - protocol: TCP
    port: 8080
```
